version: "3.8"

services:
  calibre-web:
    image: crocodilestick/calibre-web-automated:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8083
    volumes:
      - ${APP_DATA_DIR}/data/cwa-config:/config
      - ${APP_DATA_DIR}/data/ingest:/cwa-book-ingest
      - ${APP_DATA_DIR}/data/library:/calibre-library
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRUSTED_PROXY_COUNT=2
    x-runtipi:
      internal_port: 8083
      is_main: true
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.calibre-web-web-redirect.redirectscheme.scheme: https
      traefik.http.services.calibre-web.loadbalancer.server.port: 8083
      traefik.http.routers.calibre-web-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.calibre-web-insecure.entrypoints: web
      traefik.http.routers.calibre-web-insecure.service: calibre-web
      traefik.http.routers.calibre-web-insecure.middlewares: calibre-web-web-redirect
      traefik.http.routers.calibre-web.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.calibre-web.entrypoints: websecure
      traefik.http.routers.calibre-web.service: calibre-web
      traefik.http.routers.calibre-web.tls.certresolver: myresolver

networks:
  tipi_main_network:
    external: true
x-runtipi:
  schema_version: 2
