version: "3.8"

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.27
    restart: unless-stopped
    ports:
      - 8100:8083
      - 9090:9090
    volumes:
      - ${APP_DATA_DIR}/calibre-web/books:/books
      - ${APP_DATA_DIR}/calibre-web/config:/config
      - ${APP_DATA_DIR}/calibre-web/calibre-binaries:/app/calibre
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre|ghcr.io/kosync/kosync-mod
      - KOSYNC_ENABLED=true
      - KOSYNC_PORT=9090
      - KOSYNC_DATABASE=/config/kosync.db
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    x-runtipi:
      internal_port: 8083
      is_main: true
x-runtipi:
  schema_version: 2